eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9010
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/singleqi/springcloud
          search-paths: config-resource
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
# actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management:
  endpoints:
    web:
      exposure:
        include: "*"
