#和重试机制相关的配置有如下四个：
spring:
  rabbitmq:
    host: 192.168.12.3
    port: 5672
    username: cloudchef
    password: c10udch3f
  cloud:
    config:
      retry:
        # 配置重试次数，默认为6
        max-attempts: 6
        # 间隔乘数，默认1.1
        multiplier: 1.1
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
        # 最大间隔时间，默认2000ms
        max-interval: 2000
# actuator在boot2.0调整后开关web端点的配置，*代表开启所有
management:
  endpoints:
    web:
      exposure:
        include: "*"