eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
server:
  port: 9005
zuul:
  routes:
    api-a:
      path: /api-feign/**
      serviceId: hystrix-feign-consumer
    api-b:
      path: /api-ribbon/**
      serviceId: hystrix-ribbon-consumer

