eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: hystrix-dashboard-turbine
server:
  port: 9000
# 熔断器turbine
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: HYSTRIX-FEIGN-CONSUMER, HYSTRIX-RIBBON-CONSUMER